"""initial_schema

Revision ID: 0dbf3ce903e9
Revises: 
Create Date: 2026-04-18 09:02:25.375070+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dbf3ce903e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('centroid', Vector(dim=384), nullable=True),
    sa.Column('article_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('decay_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('top_sources', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_last_activity', 'clusters', ['last_activity'], unique=False)
    op.create_index('ix_clusters_status', 'clusters', ['status'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_interval', sa.Integer(), server_default='600', nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('top_image_url', sa.Text(), nullable=True),
    sa.Column('simhash', sa.Numeric(precision=39, scale=0), server_default='0', nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('quality_score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('extraction_method', sa.Text(), server_default='trafilatura', nullable=False),
    sa.Column('raw_html_size', sa.Integer(), nullable=True),
    sa.Column('content_length', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_cluster_id'), 'articles', ['cluster_id'], unique=False)
    op.create_index('ix_articles_embedding_hnsw', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_articles_extracted_at', 'articles', ['extracted_at'], unique=False)
    op.create_index(op.f('ix_articles_feed_id'), 'articles', ['feed_id'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_feed_id'), table_name='articles')
    op.drop_index('ix_articles_extracted_at', table_name='articles')
    op.drop_index('ix_articles_embedding_hnsw', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_articles_cluster_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('feeds')
    op.drop_index('ix_clusters_status', table_name='clusters')
    op.drop_index('ix_clusters_last_activity', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
