"""SQLAlchemy ORM table definitions for VyomaCast.

These DeclarativeBase models define the PostgreSQL schema and serve as the
single source of truth for Alembic migrations (``alembic --autogenerate``).

Table design strictly follows the data contracts from §10.1:
    * ``feeds``    — RSS/Atom feed sources
    * ``articles`` — Extracted news articles with 384-dim pgvector embeddings
    * ``clusters`` — Story clusters with centroid vectors

Key constraints:
    * articles.url_hash — UNIQUE index (dedup identity)
    * articles.embedding — HNSW index with cosine ops (semantic search)
    * clusters.id — PK is also the ON CONFLICT target for version-guarded upsert
    * feeds.url — UNIQUE index (idempotent feed registration)
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Optional
from uuid import UUID, uuid4

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy import Index
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ────────────────────────────────────────────────────────────────────────────
# Base
# ────────────────────────────────────────────────────────────────────────────


class Base(DeclarativeBase):
    """DeclarativeBase for all VyomaCast tables.

    Provides the shared ``metadata`` object consumed by Alembic for
    autogenerated migrations.
    """

    pass


# ────────────────────────────────────────────────────────────────────────────
# Feeds
# ────────────────────────────────────────────────────────────────────────────


class FeedRow(Base):
    """RSS/Atom feed source — maps to domain ``Feed``."""

    __tablename__ = "feeds"

    id: Mapped[UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid4,
    )
    url: Mapped[str] = mapped_column(sa.Text, unique=True, nullable=False)
    name: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)

    # Polling state
    last_polled_at: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True), nullable=True,
    )
    poll_interval: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="600",
    )
    next_poll_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )

    # Tracking
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, server_default="active",
    )
    error_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="0",
    )
    last_error: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    etag: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    last_modified: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)

    # Metadata
    article_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="0",
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )


# ────────────────────────────────────────────────────────────────────────────
# Articles
# ────────────────────────────────────────────────────────────────────────────


class ArticleRow(Base):
    """News article — maps to domain ``Article``."""

    __tablename__ = "articles"
    __table_args__ = (
        # HNSW index for fast cosine similarity search via pgvector
        Index(
            "ix_articles_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # Composite index for the write-back query (recent embeddings fallback)
        Index("ix_articles_extracted_at", "extracted_at"),
    )

    id: Mapped[UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid4,
    )

    # Identity
    url: Mapped[str] = mapped_column(sa.Text, nullable=False)
    url_hash: Mapped[str] = mapped_column(
        sa.String(64), unique=True, nullable=False, index=True,
    )
    feed_id: Mapped[Optional[UUID]] = mapped_column(
        sa.Uuid,
        sa.ForeignKey("feeds.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Content
    title: Mapped[str] = mapped_column(sa.Text, nullable=False)
    content: Mapped[str] = mapped_column(sa.Text, nullable=False)
    authors: Mapped[list[str]] = mapped_column(
        ARRAY(sa.Text), nullable=False, server_default="{}",
    )
    language: Mapped[str] = mapped_column(
        sa.String(10), nullable=False, server_default="en",
    )
    top_image_url: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)

    # Deduplication fingerprints
    simhash: Mapped[int] = mapped_column(
        sa.Numeric(precision=39, scale=0), nullable=False, server_default="0",
    )
    embedding: Mapped[Optional[list[float]]] = mapped_column(
        Vector(384), nullable=True,
    )

    # Clustering
    cluster_id: Mapped[Optional[UUID]] = mapped_column(
        sa.Uuid,
        sa.ForeignKey("clusters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Quality & extraction metadata
    quality_score: Mapped[float] = mapped_column(
        sa.Float, nullable=False, server_default="0.0",
    )
    extraction_method: Mapped[str] = mapped_column(
        sa.Text, nullable=False, server_default="'trafilatura'",
    )
    raw_html_size: Mapped[Optional[int]] = mapped_column(sa.Integer, nullable=True)
    content_length: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="0",
    )

    # Timestamps
    published_at: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True), nullable=True,
    )
    extracted_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )

    # Optimistic-concurrency version
    version: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="1",
    )

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )


# ────────────────────────────────────────────────────────────────────────────
# Clusters
# ────────────────────────────────────────────────────────────────────────────


class ClusterRow(Base):
    """Story cluster — maps to domain ``Cluster``."""

    __tablename__ = "clusters"
    __table_args__ = (
        Index("ix_clusters_status", "status"),
        Index("ix_clusters_last_activity", "last_activity"),
    )

    id: Mapped[UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid4,
    )

    # Cluster state
    label: Mapped[str] = mapped_column(sa.Text, nullable=False)
    centroid: Mapped[Optional[list[float]]] = mapped_column(
        Vector(384), nullable=True,
    )
    article_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="1",
    )

    # Temporal decay
    decay_score: Mapped[float] = mapped_column(
        sa.Float, nullable=False, server_default="1.0",
    )
    last_activity: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )

    # Metadata
    top_sources: Mapped[list[str]] = mapped_column(
        ARRAY(sa.Text), nullable=False, server_default="{}",
    )

    # Status
    status: Mapped[str] = mapped_column(
        sa.Text, nullable=False, server_default="active",
    )

    # Optimistic-concurrency version
    version: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="1",
    )

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False,
        server_default=sa.func.now(),
    )
